# Generated by Django 3.1.7 on 2021-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('sent_id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sent_id'],
            },
        ),
    ]
