# Generated by Django 3.1.7 on 2021-04-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('polarity', models.CharField(max_length=8)),
                ('modality', models.CharField(max_length=8)),
                ('trigger', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('sent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation_app.sentences')),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
    ]
