# Generated by Django 3.1.7 on 2021-04-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_arguments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('arg_text', models.CharField(max_length=300)),
                ('arg_role', models.CharField(max_length=300)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation_app.events')),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
    ]
