# Generated by Django 3.1.7 on 2021-04-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0003_event_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='review_comments',
            field=models.TextField(help_text='Enter your review / comments on the annotation', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
