# Generated by Django 3.1.7 on 2021-04-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0004_auto_20210408_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='sent_review_comments',
            field=models.TextField(help_text='Enter your review/comments on the annotation', max_length=1000, null=True),
        ),
    ]
