# Generated by Django 3.1.7 on 2021-04-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0005_sentences_sent_review_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Enter your review / comments on the annotation', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sent_review_comments',
            field=models.TextField(blank=True, help_text='Enter your review/comments on the annotation', max_length=1000, null=True),
        ),
    ]
