# Generated by Django 3.1.7 on 2021-04-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0006_auto_20210408_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='annotator_id',
            field=models.CharField(default='annotator1', max_length=10),
        ),
        migrations.AddField(
            model_name='sentences',
            name='annotator_id',
            field=models.CharField(default='annotator1', max_length=10),
        ),
    ]
