# Generated by Django 3.1.7 on 2021-04-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0007_auto_20210408_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_validation_text', models.TextField(blank=True, help_text='Enter your review / comments on the annotation', max_length=1000, null=True)),
                ('annotator_id', models.CharField(default='annotator1', max_length=10)),
                ('validated', models.IntegerField()),
                ('sent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation_app.sentences')),
            ],
        ),
    ]
