# Generated by Django 3.1.7 on 2021-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_app', '0010_event_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='modality_cue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='polarity_cue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
